# canary_ai/analyzer.py
import os
import time
import google.generativeai as genai
from google.api_core import exceptions as google_exceptions
import json
import traceback
import logging

logger = logging.getLogger(__name__)

# --- Configuration ---
HIGH_TEMP_THRESHOLD = 110.0
HIGH_RPM_THRESHOLD = 4500
LOW_SPEED_THRESHOLD = 10
GEMINI_MODEL_NAME = "gemini-1.5-flash"

# --- Configure Google GenAI ---
LLM_ENABLED = False
try:
    api_key = os.environ.get("GOOGLE_API_KEY")
    if not api_key: raise ValueError("GOOGLE_API_KEY missing")
    genai.configure(api_key=api_key)
    logger.info(f"GenAI OK: Model={GEMINI_MODEL_NAME}.")
    LLM_ENABLED = True
except Exception as e: logger.warning(f"GenAI FAIL: {e}. LLM disabled.")

# --- DTC Info ---
# Updated based on user-provided list + kept internal flags
DTC_DESCRIPTIONS = {
    "P0102": "MAF Sensor Circuit Low", # Corrected description
    "P0301": "Cylinder 1 Misfire Detected",
    "U0100": "Momentary loss of communication between control modules",
    "C0035": "Left Front Wheel Speed Sensor Malfunction",
    "P0128": "Coolant Thermostat (Temperature Below Threshold)", # Slightly better phrasing
    "C0073": "Intermittent chassis-related fault (may self-correct)",
    "P03D0": "Transient issue in ignition/misfire detection system",
    # Internal derived keys
    "CRITICAL_FLAG_ACTIVE": "Generic Critical Flag Active (From Status Byte 0-3)",
    "HEALABLE_FLAG_ACTIVE": "Generic Healable Flag Active (From Status Byte 4-7)",
    "AI_ANOMALY": "AI Detected Potential Anomaly in Sensor Data"
}

# --- Known Issues & Actions ---
# Conditions use simple metrics dict {'rpm':X,'speed':Y,'temp':Z}
# and dtcs set {'P0123', 'AI_ANOMALY', 'CRITICAL_FLAG_ACTIVE', ...}
ISSUE_DEFINITIONS = {
    # --- Metric Based Rules ---
    "HIGH_ENGINE_TEMP": {
        "severity": "CRITICAL",
        "conditions": lambda metrics, dtcs: metrics.get("temp", 0) > HIGH_TEMP_THRESHOLD,
        "action_type": "DIY_DIAGNOSTIC", "self_heal_possible": False, "heal_command": None,
        "llm_context": "Engine temp metric > threshold."
    },
    "HIGH_RPM_LOW_SPEED": {
         "severity": "WARNING",
         "conditions": lambda metrics, dtcs: metrics.get("rpm", 0) > HIGH_RPM_THRESHOLD and metrics.get("speed", LOW_SPEED_THRESHOLD + 1) < LOW_SPEED_THRESHOLD,
         "action_type": "INFO", "self_heal_possible": False, "heal_command": None,
         "llm_context": "High RPM at low speed detected."
     },

    # --- Rules for Specific DTCs Received ---
    "DTC_P0102": {
        "severity": "WARNING", "conditions": lambda metrics, dtcs: "P0102" in dtcs,
        "action_type": "DIY_DIAGNOSTIC", "self_heal_possible": False, "heal_command": None,
        "llm_context": "DTC P0102 (MAF Sensor Circuit Low) is active." },
     "DTC_P0128": {
        "severity": "WARNING", "conditions": lambda metrics, dtcs: "P0128" in dtcs,
        "action_type": "SELF_HEAL_ATTEMPT", "self_heal_possible": True, "heal_command": "CLEAR_DTCS",
        "llm_context": "DTC P0128 (Coolant Thermostat) active." },
    "DTC_P0301": {
        "severity": "ERROR", "conditions": lambda metrics, dtcs: "P0301" in dtcs,
        "action_type": "DIY_REPAIR", "self_heal_possible": True, "heal_command": "CLEAR_DTCS",
        "llm_context": "DTC P0301 (Cyl 1 Misfire) active." },
     "DTC_U0100": {
        "severity": "ERROR", "conditions": lambda metrics, dtcs: "U0100" in dtcs,
        "action_type": "MECHANIC", "self_heal_possible": False, "heal_command": None,
        "llm_context": "DTC U0100 (Lost Comm with ECM/PCM) active." },
     "DTC_C0035": {
        "severity": "WARNING", "conditions": lambda metrics, dtcs: "C0035" in dtcs,
        "action_type": "DIY_DIAGNOSTIC", "self_heal_possible": False, "heal_command": None,
        "llm_context": "DTC C0035 (Wheel Speed Sensor) active." },
    "DTC_C0073": {
        "severity": "INFO", "conditions": lambda metrics, dtcs: "C0073" in dtcs,
        "action_type": "INFO", "self_heal_possible": True, "heal_command": "CLEAR_DTCS",
        "llm_context": "DTC C0073 (Intermittent Chassis Fault) active." },
     "DTC_P03D0": {
        "severity": "INFO", "conditions": lambda metrics, dtcs: "P03D0" in dtcs,
        "action_type": "INFO", "self_heal_possible": True, "heal_command": "CLEAR_DTCS",
        "llm_context": "DTC P03D0 (Transient Ignition) active." },

    # --- Rules for Derived Flags/AI (As generated by main.py) ---
    "CRITICAL_FLAG_DETECTED": { # Renamed slightly
       "severity": "ERROR", # May need adjustment based on specific flags
       "conditions": lambda metrics, dtcs: "CRITICAL_FLAG_ACTIVE" in dtcs,
       "action_type": "MECHANIC", "self_heal_possible": False, "heal_command": None,
       "llm_context": "A critical status flag bit (0-3) is active." },
    "HEALABLE_FLAG_DETECTED": { # Renamed slightly
       "severity": "WARNING",
       "conditions": lambda metrics, dtcs: "HEALABLE_FLAG_ACTIVE" in dtcs,
       "action_type": "SELF_HEAL_ATTEMPT", "self_heal_possible": True, "heal_command": "CLEAR_DTCS", # Or specific heal based on bits?
       "llm_context": "A healable status flag bit (4-7) is active. Attempting clear." },
    "AI_ANOMALY_DETECTED": {
        "severity": "WARNING", "conditions": lambda metrics, dtcs: "AI_ANOMALY" in dtcs,
        "action_type": "INFO", "self_heal_possible": False, "heal_command": None,
        "llm_context": "AI system detected an unusual data pattern." }
}

# --- LLM Instruction Generation ---
def get_llm_instructions(issue_key, issue_details_dict, metrics, dtcs):
    """ Calls Gemini API for instructions, uses issue_details_dict correctly. """
    # (Implementation is identical to the previous version, which was correct)
    if not LLM_ENABLED: return f"LLM Disabled. Issue: {issue_key}. Info: {issue_details_dict.get('llm_context', 'N/A')}"
    action_type = issue_details_dict.get("action_type", "INFO")
    task_description = ""
    if action_type in ["DIY_DIAGNOSTIC", "DIY_REPAIR", "MECHANIC"]: task_description = "Provide concise step-by-step owner instructions."
    elif action_type == "INFO": return issue_details_dict.get('llm_context', 'N/A')
    elif action_type == "SELF_HEAL_ATTEMPT": return f"{issue_details_dict.get('llm_context', 'N/A')} Automated recovery log attempt possible."
    else: return f"Acknowledged: {issue_key}. {issue_details_dict.get('llm_context', 'N/A')}"
    if not task_description: return f"Handled: {issue_key}"

    logger.info(f"Querying Gemini for: {issue_key}")
    active_dtc_list = ", ".join(sorted([f"{c} ({DTC_DESCRIPTIONS.get(c, '?')})" for c in dtcs])) or "None"
    rpm = metrics.get("rpm", "N/A"); temp = metrics.get("temp", "N/A"); speed = metrics.get("speed", "N/A")
    metrics_summary = f"Temp={temp} C, RPM={rpm}, Speed={speed} km/h"
    full_prompt = f"""Act as AI Car Assistant. Basic DIY user. Task: {task_description} Be concise (<150 words), safe, use plain text paragraphs. Recommend mechanic if needed. Input Context: {issue_details_dict.get('llm_context', 'N/A')}. Issue: {issue_key}. Active DTCs: {active_dtc_list}. Metrics: {metrics_summary}. Owner Instructions:"""
    try:
        model = genai.GenerativeModel(GEMINI_MODEL_NAME)
        response = model.generate_content(full_prompt, generation_config={"max_output_tokens": 200, "temperature": 0.6})
        if not response.candidates or not response.candidates[0].content.parts: raise ValueError(f"Blocked/Empty: {response.prompt_feedback}")
        return response.text.strip()
    except Exception as e: logger.error(f"LLM Error {issue_key}: {e}"); return f"Error getting AI instructions."

# --- Main analysis function ---
def analyze_vehicle_state(latest_metrics, active_dtcs_set):
    """ Analyzes current state, finds primary issue, gets instructions. """
    # (Implementation is identical to the previous version, which was correct
    #  in how it processed inputs and called get_llm_instructions)
    issues_found = []; primary_issue_details = None; highest_severity_level = 0
    severity_map = {"INFO": 1, "WARNING": 2, "ERROR": 3, "CRITICAL": 4, "OK": 0}
    metrics_dict = latest_metrics if isinstance(latest_metrics, dict) else {}
    dtc_set = active_dtcs_set if isinstance(active_dtcs_set, set) else set()

    for key, definition in ISSUE_DEFINITIONS.items():
        try:
            if definition.get("conditions") and definition["conditions"](metrics_dict, dtc_set):
                level = severity_map.get(definition.get("severity", "INFO"), 1)
                issue_data = definition.copy(); issue_data["key"] = key; issue_data["level"] = level
                issues_found.append(issue_data) # Store detailed issue data
                if level > highest_severity_level: highest_severity_level = level; primary_issue_details = issue_data
        except Exception as e: logger.error(f"Cond Eval Error {key}: {e}"); traceback.print_exc()

    final_action = {"type": "NONE", "instructions": "All systems nominal.", "key": None, "self_heal_possible": False}
    overall_status = "OK"
    if primary_issue_details:
        overall_status = primary_issue_details["severity"]
        final_action.update({ k: v for k, v in primary_issue_details.items() if k in ["type", "key", "self_heal_possible"]}) # Use keys directly
        final_action["type"] = primary_issue_details["action_type"] # Ensure type is correct key name
        final_action["instructions"] = get_llm_instructions(primary_issue_details["key"], primary_issue_details, metrics_dict, dtc_set)

    # Final UI output preparation
    simple_issues = [{"key": iss["key"], "severity": iss["severity"]} for iss in issues_found]
    active_dtc_list_for_ui = [{"code": code, "desc": DTC_DESCRIPTIONS.get(code, "Desc unavailable")} for code in sorted(list(dtc_set))]

    return {"status": overall_status, "issues": simple_issues, "action": final_action, "active_dtcs": active_dtc_list_for_ui}


# --- Example Usage ---
if __name__ == "__main__": # (Keep example tests as they were)
   # ... (Example tests for OK, P0128, P0301, AI_ANOMALY, High Temp) ...
   pass # Add specific tests for new DTCs if desired
